# Generated by Django 4.0.5 on 2022-08-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
